# Generated by Django 3.0 on 2024-06-14 13:28

from django.db import migrations, models
# from django.forms.models import model_to_dict
# from profiles.models import Profile as new_Profile
# from oc_lettings_site.models import Profile as old_Profile

# def copy_data(apps, schema_editor):
    # # Copy Profile data
    # old_addresses = old_Profile.objects.all()
    # new_addresses = [
    #     new_Profile(
    #         user=old_address.user,
    #         favorite_city=old_address.favorite_city,
    #     )
    #     for old_address in old_addresses
    # ]
    # new_Profile.objects.bulk_create(new_addresses)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(copy_data),
    ]
