# Generated by Django 3.0 on 2024-06-14 13:28

from django.db import migrations, models
# from django.forms.models import model_to_dict
# from lettings.models import Address as new_Address, Letting as new_Letting
# from oc_lettings_site.models import Address as old_Address, Letting as old_Letting

# def copy_data(apps, schema_editor):
#     # Copy Address data
#     old_addresses = old_Address.objects.all()
#     new_addresses = [
#         new_Address(
#             number=old_address.number,
#             street=old_address.street,
#             city=old_address.city,
#             state=old_address.state,
#             zip_code=old_address.zip_code,
#             country_iso_code=old_address.country_iso_code,
#         )
#         for old_address in old_addresses
#     ]
#     new_Address.objects.bulk_create(new_addresses)
#     address_fields = ['number', 'street', 'city', 'state', 'zip_code', 'country_iso_code']

#     # Copy Letting data
#     old_lettings = old_Letting.objects.all()
#     new_lettings = [
#         new_Letting(
#             title=old_letting.title,
#             address=new_Address.objects.get(**model_to_dict(old_letting.address, fields=address_fields)),
#         )
#         for old_letting in old_lettings
#     ]
#     new_Letting.objects.bulk_create(new_lettings)

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(copy_data),
    ]
