name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
        env:
          DJANGO_SETTINGS_MODULE: oc_lettings_site.settings

      - name: Check coverage
        run: |
          coverage report --fail-under=80

  build_and_push_docker:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ocr_p13:${{ github.sha }} .

      - name: Push Docker image with commit SHA
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ocr_p13:${{ github.sha }}

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -d '{"serviceId": "srv-cq4knvo8fa8c73fr5h3g"}' \s
          https://api.render.com/v1/services/srv-cq4knvo8fa8c73fr5h3g/deploys
