name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report

      - name: Check coverage
        run: |
          coverage report --fail-under=80

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build . -t myapp:${{ github.sha }}

      - name: Push Docker image
        run: docker push clementboloch/ocr_p13:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Render
        run: |
          # Ajouter ici les étapes pour déployer sur Render ou un autre fournisseur de services
